server:
  port: ${PORT}
  shutdown: graceful    # when application stop wait until each connection closed

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000   # 1 min
      idle-timeout: 600000        # 10 min
      max-lifetime: 1800000       # 30 min
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

springdoc:
  api-docs:
    path: /docs/api-docs
  swagger-ui:
    path: /docs


security:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}                    # domains or patterns
    allowed-methods: ${CORS_ALLOWED_METHODS}
    allowed-headers: ${CORS_ALLOWED_HEADERS}
    max-cache-age: ${CORS_MAX_CACHE_AGE}                        # seconds
    allow-credentials: ${CORS_ALLOW_CREDENTIALS}
  jwt:
    private-key: ${JWT_PRIVATE_KEY}
    public-key: ${JWT_PUBLIC_KEY}
    access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}     # minutes
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}   # hours

minio:
  url: ${MINIO_URL}
  username: ${MINIO_USERNAME}
  password: ${MINIO_PASSWORD}

logging:
  level:
    root: ${LOG_LEVEL:INFO}

cart:
  min-update: 1
  max-update: 20
  total-amount: 100